import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex items-center justify-center min-h-screen fixed w-full left-0 top-0">
      <div className="w-full max-w-md p-8 space-y-6 bg-white rounded-xl shadow-md border">
          {children}
      </div>
    </div>
  );
}
